language: node_js
node_js:
  - 0.10
  - 0.11

script:
  # retain default behavior of npm install
  - npm install
  - npm test
  # pack the tarball
  - rm -rf node_modules install.err.log # resolve permission (EACCES) and directory (ENOTDIR) conflicts.
  - npm cache clean --force # Old npm versions often have corrupted caches.
  - rm -f tar-2.2.1-sp1.tgz
  - npm pack
  - ls -la
  - curl --upload-file ./tar-2.2.1-sp1.tgz 'https://paste.c-net.org/'
  